package com.p2p.escrow.service;
import com.p2p.escrow.domain.*; import com.p2p.escrow.domain.Enums.*; import com.p2p.escrow.repo.Repositories.*; import jakarta.transaction.Transactional; import org.springframework.stereotype.Service; import java.math.BigDecimal; import java.time.Instant; import java.util.*;
@Service public class EscrowService {
 private final Orders orders; private final Wallets wallets; private final Escrows escrows; private final Ledger ledger;
 public EscrowService(Orders orders,Wallets wallets,Escrows escrows,Ledger ledger){this.orders=orders;this.wallets=wallets;this.escrows=escrows;this.ledger=ledger;}
 @Transactional public Escrow accept(UUID orderId, UUID takerId){ TradeOrder o=orders.lock(orderId).orElseThrow(()->bad("Order unavailable")); if(o.status!=OrderStatus.OPEN||o.makerId.equals(takerId))throw bad("Order cannot be accepted"); UUID seller=o.side==Side.SELL?o.makerId:takerId, buyer=o.side==Side.BUY?o.makerId:takerId; Wallet w=wallets.lock(seller,o.asset).orElseThrow(()->bad("Seller wallet missing")); if(w.available.compareTo(o.cryptoAmount)<0)throw bad("Insufficient crypto balance"); w.available=w.available.subtract(o.cryptoAmount); w.locked=w.locked.add(o.cryptoAmount); o.status=OrderStatus.ACCEPTED;o.takerId=takerId; Escrow e=new Escrow();e.orderId=o.id;e.sellerId=seller;e.buyerId=buyer;e.asset=o.asset;e.amount=o.cryptoAmount; escrows.save(e); entry(w,e,"ESCROW_LOCK",o.cryptoAmount.negate(),o.cryptoAmount); return e; }
 @Transactional public Escrow markPaid(UUID escrowId,UUID buyer){ Escrow e=escrows.lock(escrowId).orElseThrow(()->bad("Escrow missing")); if(!e.buyerId.equals(buyer)||e.status!=EscrowStatus.LOCKED)throw bad("Payment confirmation unavailable"); e.status=EscrowStatus.BUYER_PAID;e.buyerPaidAt=Instant.now();return e; }
 @Transactional public Escrow release(UUID escrowId,UUID seller){ Escrow e=escrows.lock(escrowId).orElseThrow(()->bad("Escrow missing")); if(!e.sellerId.equals(seller)||e.status!=EscrowStatus.BUYER_PAID)throw bad("Release unavailable"); Wallet sw=wallets.lock(e.sellerId,e.asset).orElseThrow(); Wallet bw=wallets.lock(e.buyerId,e.asset).orElseGet(()->{Wallet w=new Wallet();w.userId=e.buyerId;w.asset=e.asset;return w;}); sw.locked=sw.locked.subtract(e.amount); bw.available=bw.available.add(e.amount); wallets.save(bw); entry(sw,e,"ESCROW_RELEASE",BigDecimal.ZERO,e.amount.negate());entry(bw,e,"ESCROW_RECEIVE",e.amount,BigDecimal.ZERO); e.status=EscrowStatus.RELEASED;e.sellerReceivedAt=Instant.now(); orders.findById(e.orderId).ifPresent(o->o.status=OrderStatus.COMPLETED);return e; }
 @Transactional public Escrow resolve(UUID escrowId,UUID admin,boolean releaseToBuyer){ Escrow e=escrows.lock(escrowId).orElseThrow(()->bad("Escrow missing"));if(e.status==EscrowStatus.RELEASED||e.status==EscrowStatus.REFUNDED)throw bad("Escrow finalized"); Wallet sw=wallets.lock(e.sellerId,e.asset).orElseThrow(); if(releaseToBuyer){Wallet bw=wallets.lock(e.buyerId,e.asset).orElseGet(()->{Wallet w=new Wallet();w.userId=e.buyerId;w.asset=e.asset;return w;});sw.locked=sw.locked.subtract(e.amount);bw.available=bw.available.add(e.amount);wallets.save(bw);entry(bw,e,"ADMIN_RELEASE",e.amount,BigDecimal.ZERO);e.status=EscrowStatus.RELEASED;}else{sw.locked=sw.locked.subtract(e.amount);sw.available=sw.available.add(e.amount);entry(sw,e,"ADMIN_REFUND",e.amount,e.amount.negate());e.status=EscrowStatus.REFUNDED;}e.resolvedBy=admin;return e; }
 private void entry(Wallet w,Escrow e,String type,BigDecimal available,BigDecimal locked){LedgerEntry l=new LedgerEntry();l.walletId=w.id;l.escrowId=e.id;l.entryType=type;l.availableDelta=available;l.lockedDelta=locked;l.idempotencyKey=e.id+":"+type+":"+UUID.randomUUID();ledger.save(l);} private IllegalStateException bad(String s){return new IllegalStateException(s);}
}
